version: '3'

services:
  database: 
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - ./docker/postgres-db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432